/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rosepetalproject;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author YUGHIE
 */
public class RosePetalGame extends javax.swing.JFrame {

    /**
     * Creates new form RosePetalGame
     */
    public RosePetalGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon2 = new javax.swing.JLabel();
        lblIcon3 = new javax.swing.JLabel();
        lblIcon4 = new javax.swing.JLabel();
        lblIcon5 = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        btnGuessPetal = new javax.swing.JButton();
        btnRollDice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rosepetalproject/1.png"))); // NOI18N
        lblIcon2.setText("jLabel1");

        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rosepetalproject/1.png"))); // NOI18N
        lblIcon3.setText("jLabel1");

        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rosepetalproject/1.png"))); // NOI18N
        lblIcon4.setText("jLabel1");

        lblIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rosepetalproject/1.png"))); // NOI18N
        lblIcon5.setText("jLabel1");

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/rosepetalproject/1.png"))); // NOI18N
        lblIcon1.setText("jLabel1");

        btnGuessPetal.setText("GUESS NUMBER OF PETAL");

        btnRollDice.setText("ROLL DICE");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        jLabel1.setText("GUESS: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuessPetal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lblIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIcon2)
                    .addComponent(lblIcon3)
                    .addComponent(lblIcon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIcon4)
                    .addComponent(lblIcon5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuessPetal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int petal = 0;
    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        // TODO add your handling code here:
        
        String[] icons = {
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\1.png",
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\2.png",
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\3.png",
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\4.png",
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\5.png",
            "D:\\Documents\\Java Programming\\Programming-Activities\\RosePetalProject\\src\\main\\java\\com\\mycompany\\rosepetalproject\\6.png"
        };
        
        Random rand = new Random();
        
        int index1 = rand.nextInt(icons.length);
        int index2 = rand.nextInt(icons.length);
        int index3 = rand.nextInt(icons.length);
        int index4 = rand.nextInt(icons.length);
        int index5 = rand.nextInt(icons.length);
       
        try {
            for(int i = 0; i <=5; i ++){
               Thread thread = new Thread();
               thread.start(); 
               
               lblIcon1.setIcon(new ImageIcon(icons[index1]));
               lblIcon2.setIcon(new ImageIcon(icons[index2]));
               lblIcon3.setIcon(new ImageIcon(icons[index3]));
               lblIcon4.setIcon(new ImageIcon(icons[index4]));
               lblIcon5.setIcon(new ImageIcon(icons[index5]));
               
               
            }
                     
            
        } catch (Exception e) {
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RosePetalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RosePetalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RosePetalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RosePetalGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RosePetalGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuessPetal;
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblIcon5;
    private javax.swing.JTextField txtGuess;
    // End of variables declaration//GEN-END:variables
}
