package lecture5;

import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class LoanCalculator extends javax.swing.JFrame {

    /**
     * Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInterestRate = new javax.swing.JTextField();
        txtNumberOfYears = new javax.swing.JTextField();
        txtLoanAmount = new javax.swing.JTextField();
        btnComputeLoan = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblMonthlyPayment = new javax.swing.JLabel();
        lblTotalPayment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter yearly interest rate (i.e 8.25)");

        jLabel2.setText("Enter number of years as an interger");

        jLabel3.setText("Enter loan amount (i.e 120000.95)");

        btnComputeLoan.setText("Compute my Loan");
        btnComputeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeLoanActionPerformed(evt);
            }
        });

        lblDate.setText("jLabel4");

        lblMonthlyPayment.setText("jLabel5");

        lblTotalPayment.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(btnComputeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumberOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonthlyPayment)
                            .addComponent(lblDate)
                            .addComponent(lblTotalPayment))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumberOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnComputeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonthlyPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPayment)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double interestRate ;
    int numberOfYears;
    double loanAmount;

    
    public void displayInformation(Loan loan){         
           DecimalFormat frm = new DecimalFormat("0.00");
           
           lblDate.setText("The loan was created on " +  loan.getLoanDate());
           lblMonthlyPayment.setText("The monthly payment is " + frm.format(loan.getMonthlyPayment()));
           lblTotalPayment.setText("The total payment is " + frm.format(loan.getTotalPayment()));
       }
    public void setDataField(){
        
            
    }
    
    private void btnComputeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeLoanActionPerformed
        
        if(txtInterestRate.getText().isEmpty() || txtLoanAmount.getText().isEmpty()|| txtNumberOfYears.getText().isEmpty()) {
            try {
                interestRate = Double.parseDouble(txtInterestRate.getText());
                numberOfYears = Integer.parseInt(txtLoanAmount.getText());
                loanAmount = Double.parseDouble(txtNumberOfYears.getText());
            } catch (Exception e) {
                int option = JOptionPane.showConfirmDialog(this, "Invaid input. Do you want to set all to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);
                if(option == 0){
                    Loan loan = new Loan();
                    displayInformation(loan);
                    txtInterestRate.setText(String.valueOf(loan.getAnnualInterestRate()));
                    txtNumberOfYears.setText(String.valueOf(loan.getNumberOfYears()));
                    txtLoanAmount.setText(String.valueOf(loan.getLoanAmount()));
                }
                else if(option == 1){
                    txtInterestRate.setText("");
                    txtNumberOfYears.setText("");
                    txtLoanAmount.setText("");
                    lblDate.setText("");
                    lblMonthlyPayment.setText("");
                    lblTotalPayment.setText("");
                } 
            }
        }
        else{
            try {
                interestRate = Double.parseDouble(txtInterestRate.getText());
                numberOfYears = Integer.parseInt(txtNumberOfYears.getText());
                loanAmount = Double.parseDouble(txtLoanAmount.getText());
            } catch (Exception e) {
                int option = JOptionPane.showConfirmDialog(this, "Invaid input. Do you want to set all to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);
                if(option == 0){
                    Loan loan = new Loan();
                    displayInformation(loan);
                    txtInterestRate.setText(String.valueOf(loan.getAnnualInterestRate()));
                    txtNumberOfYears.setText(String.valueOf(loan.getNumberOfYears()));
                    txtLoanAmount.setText(String.valueOf(loan.getLoanAmount()));
                }
                else if (option == 1){
                    txtInterestRate.setText("");
                    txtNumberOfYears.setText("");
                    txtLoanAmount.setText("");
                    lblDate.setText("");
                    lblMonthlyPayment.setText("");
                    lblTotalPayment.setText("");
                } 
               
            }
            
            
            Loan loan = new Loan(interestRate, numberOfYears, loanAmount);
            displayInformation(loan);
            /*lblDate.setText(String.valueOf(loan.getAnnualInterestRate()));
            lblMonthlyPayment.setText(String.valueOf(loan.getNumberOfYears()));
            lblTotalPayment.setText(String.valueOf(loan.getLoanAmount()));*/
        }
       
    }//GEN-LAST:event_btnComputeLoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputeLoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMonthlyPayment;
    private javax.swing.JLabel lblTotalPayment;
    private javax.swing.JTextField txtInterestRate;
    private javax.swing.JTextField txtLoanAmount;
    private javax.swing.JTextField txtNumberOfYears;
    // End of variables declaration//GEN-END:variables
}
