package lecture5;

import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class LoanCalculator extends javax.swing.JFrame {

    /**
     * Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
        this.setTitle("Loan Calculator");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnComputeLoan = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblMonthlyPayment = new javax.swing.JLabel();
        lblTotalPayment = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInterestRate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumberOfYears = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLoanAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 46, 87));
        jPanel1.setName(""); // NOI18N

        btnComputeLoan.setText("Compute my Loan");
        btnComputeLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeLoanActionPerformed(evt);
            }
        });

        lblDate.setForeground(new java.awt.Color(255, 255, 255));

        lblMonthlyPayment.setForeground(new java.awt.Color(255, 255, 255));

        lblTotalPayment.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(28, 22, 71));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(194, 196, 209));
        jLabel1.setText("Enter yearly interest rate (i.e 8.25)");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(194, 196, 209));
        jLabel2.setText("Enter number of years as an interger");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(194, 196, 209));
        jLabel3.setText("Enter loan amount (i.e 120000.95)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumberOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumberOfYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMonthlyPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(btnComputeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 221, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComputeLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonthlyPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    double interestRate = 0;
    int numberOfYears = 0;
    double loanAmount = 0;
    

    
    public void displayInformation(Loan loan){         
           DecimalFormat frm = new DecimalFormat("0.00");
           
           lblDate.setText("The loan was created on " +  loan.getLoanDate());
           lblMonthlyPayment.setText("The monthly payment is " + frm.format(loan.getMonthlyPayment()));
           lblTotalPayment.setText("The total payment is " + frm.format(loan.getTotalPayment()));
       }
    
    public void clearFields(){
        txtInterestRate.setText("");
        txtNumberOfYears.setText("");
        txtLoanAmount.setText("");
        lblDate.setText("");
        lblMonthlyPayment.setText("");
        lblTotalPayment.setText("");
        interestRate = 0;
        numberOfYears = 0;
        loanAmount = 0;
    }

    
    private void btnComputeLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeLoanActionPerformed
          
        try{
            interestRate = Double.parseDouble(txtInterestRate.getText());
            numberOfYears = Integer.parseInt(txtNumberOfYears.getText());
            loanAmount = Double.parseDouble(txtLoanAmount.getText()); 
            
            
                
            
        }
        catch(NumberFormatException e){
            if(e.getMessage().matches("empty String")){
                Loan loan = new Loan();
                
                //INTEREST RATE IS EMPTY
                if(txtInterestRate.getText().isEmpty()){
                    

                    int option = JOptionPane.showConfirmDialog(this, "Interest Rate is Empty. Do you want to set it to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);

                    if(option == 0){         
                        interestRate = loan.getAnnualInterestRate();
                        txtInterestRate.setText(String.valueOf(interestRate));
                    }
                    else if(option == 1){
                        clearFields();
                    } 

                }
                //NUMBER OF YEARS IS EMPTY
                if(txtNumberOfYears.getText().isEmpty()){
                    
                    int option = JOptionPane.showConfirmDialog(this, "Interest Rate is Empty. Do you want to set it to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);

                    if(option == 0){         
                        numberOfYears = loan.getNumberOfYears();
                        txtNumberOfYears.setText(String.valueOf(numberOfYears));
                    }
                    else if(option == 1){
                        clearFields();
                    } 

                }
                //LOAN AMOUNT IS EMPTY
                if(txtLoanAmount.getText().isEmpty()){               

                   int option = JOptionPane.showConfirmDialog(this, "Loan Amount is Empty. Do you want to set it to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);

                    if(option == 0){         
                        loanAmount = loan.getLoanAmount();
                        txtLoanAmount.setText(String.valueOf(loanAmount));
                    }
                    else if(option == 1){
                        clearFields();
                    } 
                }   
            }
            else{
                int option = JOptionPane.showConfirmDialog(this, "Invalid Format. Do you want to set all to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);
                
                if(option == 0){         
                    Loan loan = new Loan();
                    interestRate = loan.getAnnualInterestRate();
                    numberOfYears = loan.getNumberOfYears();
                    loanAmount = loan.getLoanAmount();
                    txtInterestRate.setText(String.valueOf(interestRate));
                    txtNumberOfYears.setText(String.valueOf(numberOfYears));
                    txtLoanAmount.setText(String.valueOf(loanAmount));
                       
                }
                else if(option == 1){
                    clearFields();
                }  
               
            }
        }
        catch(Exception e){
            int option = JOptionPane.showConfirmDialog(this, "ERROR 101", "ERROR", JOptionPane.YES_NO_OPTION);
            
           if (option == 0){
               System.exit(0);
           }
        }
        Loan loan1 = new Loan(interestRate, numberOfYears, loanAmount);
        displayInformation(loan1);
        
        
        /*if(txtInterestRate.getText().isEmpty() || txtLoanAmount.getText().isEmpty()|| txtNumberOfYears.getText().isEmpty()) {
            try {
                interestRate = Double.parseDouble(txtInterestRate.getText());
                numberOfYears = Integer.parseInt(txtLoanAmount.getText());
                loanAmount = Double.parseDouble(txtNumberOfYears.getText());
            } catch (Exception e) {
                int option = JOptionPane.showConfirmDialog(this, "1Invaid input. Do you want to set all to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);
                if(option == 0){
                    Loan loan = new Loan();
                    displayInformation(loan);
                    txtInterestRate.setText(String.valueOf(loan.getAnnualInterestRate()));
                    txtNumberOfYears.setText(String.valueOf(loan.getNumberOfYears()));
                    txtLoanAmount.setText(String.valueOf(loan.getLoanAmount()));
                }
                else if(option == 1){
                    txtInterestRate.setText("");
                    txtNumberOfYears.setText("");
                    txtLoanAmount.setText("");
                    lblDate.setText("");
                    lblMonthlyPayment.setText("");
                    lblTotalPayment.setText("");
                } 
            }
        }
        else{
            try {
                interestRate = Double.parseDouble(txtInterestRate.getText());
                numberOfYears = Integer.parseInt(txtNumberOfYears.getText());
                loanAmount = Double.parseDouble(txtLoanAmount.getText());
            } catch (Exception e) {
                int option = JOptionPane.showConfirmDialog(this, "2Invaid input. Do you want to set all to default?", "Notice", JOptionPane.YES_NO_CANCEL_OPTION);
                if(option == 0){
                    Loan loan = new Loan();
                    displayInformation(loan);
                    txtInterestRate.setText(String.valueOf(loan.getAnnualInterestRate()));
                    txtNumberOfYears.setText(String.valueOf(loan.getNumberOfYears()));
                    txtLoanAmount.setText(String.valueOf(loan.getLoanAmount()));
                }
                else if (option == 1){
                    txtInterestRate.setText("");
                    txtNumberOfYears.setText("");
                    txtLoanAmount.setText("");
                    lblDate.setText("");
                    lblMonthlyPayment.setText("");
                    lblTotalPayment.setText("");
                } 
               
            }
            
            
            Loan loan = new Loan(interestRate, numberOfYears, loanAmount);
            displayInformation(loan);
           
        } */
       
    }//GEN-LAST:event_btnComputeLoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputeLoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMonthlyPayment;
    private javax.swing.JLabel lblTotalPayment;
    private javax.swing.JTextField txtInterestRate;
    private javax.swing.JTextField txtLoanAmount;
    private javax.swing.JTextField txtNumberOfYears;
    // End of variables declaration//GEN-END:variables
}
