/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToe;

import javax.swing.JOptionPane;

/**
 *
 * @author YUGHIE
 */
public class FrameTicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form FrameTicTacToe
     */
    
    
    
    
    //frame 
    public FrameTicTacToe() {
        initComponents();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSlot2 = new javax.swing.JButton();
        btnSlot3 = new javax.swing.JButton();
        btnSlot1 = new javax.swing.JButton();
        btnSlot5 = new javax.swing.JButton();
        btnSlot6 = new javax.swing.JButton();
        btnSlot4 = new javax.swing.JButton();
        btnSlot8 = new javax.swing.JButton();
        btnSlot9 = new javax.swing.JButton();
        btnSlot7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        btnNewGame = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtPlayerTurn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnSlot2.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot2ActionPerformed(evt);
            }
        });

        btnSlot3.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot3ActionPerformed(evt);
            }
        });

        btnSlot1.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot1ActionPerformed(evt);
            }
        });

        btnSlot5.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot5ActionPerformed(evt);
            }
        });

        btnSlot6.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot6ActionPerformed(evt);
            }
        });

        btnSlot4.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot4ActionPerformed(evt);
            }
        });

        btnSlot8.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot8ActionPerformed(evt);
            }
        });

        btnSlot9.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot9ActionPerformed(evt);
            }
        });

        btnSlot7.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        btnSlot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jLabel1.setText("TIC TAC TOE");

        txtPlayer2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtPlayer2.setText("0");
        txtPlayer2.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("PLAYER 1");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("PLAYER 2");

        txtPlayer1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtPlayer1.setText("0");
        txtPlayer1.setEnabled(false);
        txtPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayer1ActionPerformed(evt);
            }
        });

        btnNewGame.setText("NEW GAME");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtPlayerTurn.setFont(new java.awt.Font("Dialog", 0, 70)); // NOI18N
        txtPlayerTurn.setText("X");
        txtPlayerTurn.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(txtPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean checker = true;
    int playerScore1 = 0;
    int playerScore2 = 0;
    
    public void gameStatus(){
        String button1 = btnSlot1.getText();
        String button2 = btnSlot2.getText();
        String button3 = btnSlot3.getText();
        String button4 = btnSlot4.getText();
        String button5 = btnSlot5.getText();
        String button6 = btnSlot6.getText();
        String button7 = btnSlot7.getText();
        String button8 = btnSlot8.getText();
        String button9 = btnSlot9.getText();
        
        if(button1 == "X" && button2 == "X" && button3 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
            
        }
        else if(button4 == "X" && button5 == "X" && button6 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button7 == "X" && button8 == "X" && button9 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button1 == "X" && button4 == "X" && button7 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button2 == "X" && button5 == "X" && button8 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button3 == "X" && button6 == "X" && button9 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button1 == "X" && button5 == "X" && button9 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button3 == "X" && button5 == "X" && button7 == "X"){
            playerScore1++;
            txtPlayer1.setText(String.valueOf(playerScore1));
            JOptionPane.showConfirmDialog(this, "Player X won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        
        // ~~~~~~~~~~~~~~~~~~~~~~~~PLAYER 2~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        else if(button1 == "O" && button2 == "O" && button3 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
            
        }
        else if(button4 == "O" && button5 == "O" && button6 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button7 == "O" && button8 == "O" && button9 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button1 == "O" && button4 == "O" && button7 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button2 == "O" && button5 == "O" && button8 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button3 == "O" && button6 == "O" && button9 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button1 == "O" && button5 == "O" && button9 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
        else if(button3 == "O" && button5 == "O" && button7 == "O"){
            playerScore2++;
            txtPlayer2.setText(String.valueOf(playerScore2));
            JOptionPane.showConfirmDialog(this, "Player O won", "Notice", JOptionPane.YES_OPTION);
            clear();
        }
    }
    
    public void turnChecker(){
        if(checker){
            txtPlayerTurn.setText("X");
        }
        else {
            txtPlayerTurn.setText("O");
        }
    }
    
    
    
    
    public void clear(){
        btnSlot1.setText("");
        btnSlot2.setText("");
        btnSlot3.setText("");
        btnSlot4.setText("");
        btnSlot5.setText("");
        btnSlot6.setText("");
        btnSlot7.setText("");
        btnSlot8.setText("");
        btnSlot9.setText("");
        
    }
    private void btnSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot1ActionPerformed
        if(btnSlot1.getText() == ""){
            if(checker){
                btnSlot1.setText("X");
                checker = false;
            }
            else{
                btnSlot1.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot1ActionPerformed

    private void btnSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot2ActionPerformed
        // TODO add your handling code here:
        if(btnSlot2.getText() == ""){
            if(checker){
                btnSlot2.setText("X");
                checker = false;
            }
            else{
                btnSlot2.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot2ActionPerformed

    private void btnSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot3ActionPerformed
        // TODO add your handling code here:
        if(btnSlot3.getText() == ""){
            if(checker){
                btnSlot3.setText("X");
                checker = false;
            }
            else{
                btnSlot3.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot3ActionPerformed

    private void btnSlot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot4ActionPerformed
        // TODO add your handling code here:
        if(btnSlot4.getText() == ""){
            if(checker){
                btnSlot4.setText("X");
                checker = false;
            }
            else{
                btnSlot4.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot4ActionPerformed

    private void btnSlot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot5ActionPerformed
        // TODO add your handling code here:
        if(btnSlot5.getText() == ""){
            if(checker){
                btnSlot5.setText("X");
                checker = false;
            }
            else{
                btnSlot5.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot5ActionPerformed

    private void btnSlot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot6ActionPerformed
        // TODO add your handling code here:
        if(btnSlot6.getText() == ""){
            if(checker){
                btnSlot6.setText("X");
                checker = false;
            }
            else{
                btnSlot6.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot6ActionPerformed

    private void btnSlot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot7ActionPerformed
        // TODO add your handling code here:
        if(btnSlot7.getText() == ""){
            if(checker){
                btnSlot7.setText("X");
                checker = false;
            }
            else{
                btnSlot7.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot7ActionPerformed

    private void btnSlot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot8ActionPerformed
        // TODO add your handling code here:
        if(btnSlot8.getText() == ""){
            if(checker){
                btnSlot8.setText("X");
                checker = false;
            }
            else{
                btnSlot8.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot8ActionPerformed

    private void btnSlot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot9ActionPerformed
        // TODO add your handling code here:
        if(btnSlot9.getText() == ""){
            if(checker){
                btnSlot9.setText("X");
                checker = false;
            }
            else{
                btnSlot9.setText("O");
                checker = true;
            }
        }
        gameStatus();
        turnChecker();
    }//GEN-LAST:event_btnSlot9ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        playerScore1 = 0;
        playerScore2 = 0;
        txtPlayer1.setText(String.valueOf(playerScore1));
        txtPlayer2.setText(String.valueOf(playerScore2));
        clear();
        
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void txtPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayer1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPlayer1ActionPerformed
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSlot1;
    private javax.swing.JButton btnSlot2;
    private javax.swing.JButton btnSlot3;
    private javax.swing.JButton btnSlot4;
    private javax.swing.JButton btnSlot5;
    private javax.swing.JButton btnSlot6;
    private javax.swing.JButton btnSlot7;
    private javax.swing.JButton btnSlot8;
    private javax.swing.JButton btnSlot9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    private javax.swing.JTextField txtPlayerTurn;
    // End of variables declaration//GEN-END:variables
}
