/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lecture6;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author YUGHIE
 */
public class DiceRoll extends JFrame {

    /**
     * Creates new form DiceRoll
     */
    public DiceRoll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon2 = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        lblIcon1 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecture6/image/1.JPG"))); // NOI18N

        btnRoll.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRoll.setText("ROLL DICE");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecture6/image/1.JPG"))); // NOI18N

        lblScore.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblScore.setText("SCORE: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblScore)
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblScore)
                .addGap(18, 18, 18)
                .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int score = 0;
    int random1, random2;
    
    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        // TODO add your handling code here:
        
        Random rand = new Random();
            
        String[] icons = {
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\1.JPG",
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\2.JPG",
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\3.JPG",
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\4.JPG",
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\5.JPG",
            "D:\\Documents\\Java Programming\\Programming-Activities\\Lecture6\\src\\lecture6\\image\\6.JPG"
        };
        
                  
        Thread thread = new Thread(){

            @Override
            public void run() {
                lblIcon1.setBorder(null);
                lblIcon2.setBorder(null);
                
                for (int i = 0; i < 5; i++) {
                    
                    try {   
                        
                        lblIcon1.setIcon(new ImageIcon(icons[i]));
                        lblIcon2.setIcon(new ImageIcon(icons[i]));
                        Thread.sleep(100);
                        
                    } catch (InterruptedException ex) {
                    }
                }
                random1 = rand.nextInt(icons.length);
                random2 = rand.nextInt(icons.length);
                
                lblIcon1.setIcon(new ImageIcon(icons[random1]));
                lblIcon2.setIcon(new ImageIcon(icons[random2]));
                
                LineBorder rightBorder = new LineBorder(Color.GREEN, 10);
                LineBorder wrongBorder = new LineBorder(Color.RED, 10);
                
                if(random1 == random2){
                    score++;
                    lblIcon1.setBorder(rightBorder);
                    lblIcon2.setBorder(rightBorder);
                }
                else{
                    lblIcon1.setBorder(wrongBorder);
                    lblIcon2.setBorder(wrongBorder);
                }
                lblScore.setText("Score: " + score);

            }
        };
        thread.start();        
    }//GEN-LAST:event_btnRollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceRoll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiceRoll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoll;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}
